### ISSUE TITLE
Some global parameters are not used in the code

### ISSUE THREAD

**Issue by smirik** [4xxi/resonances-fortran#5]
I was not able to find where the parameters below are used & are they actually used. The docs should be updated according to the usage.

**The parameters:**

* `allow_plotting` allows plotting graphics (works when creating metadata is allowed too)
* `plot_all`"`: if plotting is allowed, all graphics for all cases (even circulations) will be drawn
* `plot_all`"`: if plotting is allowed, all graphics for all cases (even circulations) will be drawn
* `dispose_metadata` - delete metadata after using (because it can take a lot of disk memory

**Comment by idovgalyov-4xxi** [comment]
I updated the doc
