### ISSUE TITLE
Structure the inputs & outputs into two directories

### ISSUE THREAD

**Issue by smirik** [4xxi/resonances-fortran#6]
The inputs should be collected in one directory called `input` (e.g. catalog of numbered asteroids). The same — for outputs. The structure should be changed a little bit:

1. wd -> output/results
2. aeibase -> output/aei 
3. id_matrices -> output/id_matrices
4. aei_planet -> output/aei_planets

Both directories should be presented (via gitkeep) in the repository, however, the content of them should be empty.

Gitignore should be updated (old directories should be removed, the new should be added).

**Comment by idovgalyov-4xxi** [comment]
The PR has been adopted
