### ISSUE TITLE
The functions n_from_a and a_from_n are placed has to be in the same module/file

### ISSUE THREAD

**Issue by smirik** [4xxi/resonances-fortran#7]
It looks strange that n_from_a is in global_parameters.f90 and a_from_n is in resonant_axis.f90. They would be in the same place. I prefer `resonant_axis.f90`.

**Comment by idovgalyov-4xxi** [comment]
Removed "a_from_n" function.
"n_from_a" is used in several modules so I left it in global_parameters.f90
